import { NextResponse } from 'next/server';
import { get, withTenantContext } from '@/lib/db';
import { getSessionFromCookies, checkUserSubscription } from '@/lib/auth-server';

export async function POST(request: Request) {
  try {
    const session = await getSessionFromCookies();
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const subCheck = await checkUserSubscription(session);
    if (!subCheck.active) {
      return NextResponse.json({ error: subCheck.reason }, { status: 403 });
    }

    const body = await request.json();
    const { title, data, columns, filename, format } = body;

    if (!data || !columns || !format) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    const fmtVal = (val: any) => val == null ? '' : String(val);
    const fmtUSD = (n: any) => {
      const num = Number(n || 0);
      return `$${num.toLocaleString('en-US', { minimumFractionDigits: 2 })}`;
    };

    if (format === 'xlsx') {
      const XLSX = require('xlsx');
      const wsData = [columns.map((c: any) => c.label)];
      for (const row of data) {
        wsData.push(columns.map((c: any) => {
          const val = row[c.key];
          if (c.key.includes('amount') || c.key === 'salary' || c.key === 'total') {
            return Number(val || 0);
          }
          return val == null ? '' : val;
        }));
      }
      const ws = XLSX.utils.aoa_to_sheet(wsData);
      if (wsData.length > 1) {
        const colRef = XLSX.utils.encode_col(columns.findIndex((c: any) => c.key.includes('amount') || c.key === 'salary'));
        if (colRef) {
          for (let i = 1; i < wsData.length; i++) {
            const cell = XLSX.utils.encode_cell({ r: i, c: columns.findIndex((c: any) => c.key.includes('amount') || c.key === 'salary') });
            if (ws[cell]) ws[cell].z = '#,##0.00';
          }
        }
      }
      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, title || 'Sheet1');
      const buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
      return new NextResponse(Buffer.from(buf), {
        status: 200,
        headers: {
          'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          'Content-Disposition': `attachment; filename="${filename || 'export'}"`,
        },
      });
    }

    if (format === 'docx') {
      const tableRows = data.map((row: any) =>
        `<tr>${columns.map((c: any) => `<td style="border: 1px solid #ddd; padding: 6px 8px; font-size: 11px;">${fmtVal(row[c.key])}</td>`).join('')}</tr>`
      ).join('\n');
      const thead = columns.map((c: any) => `<th style="border: 1px solid #1e3a5f; padding: 8px; font-size: 11px; font-weight: 600; background: #1e3a5f; color: #fff; text-align: left;">${c.label}</th>`).join('');
      const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${title || 'Export'}</title></head><body style="font-family: Arial; padding: 20px;">
        <h2 style="color: #1e3a5f;">${title || 'Report'}</h2>
        <table style="width: 100%; border-collapse: collapse; font-size: 12px;">${tableRows ? `<thead><tr>${thead}</tr></thead><tbody>${tableRows}</tbody>` : ''}</table>
        <p style="font-size: 10px; color: #999; margin-top: 20px;">Generated by BiasharaLedger</p>
      </body></html>`;
      return new NextResponse(html, {
        status: 200,
        headers: {
          'Content-Type': 'application/msword',
          'Content-Disposition': `attachment; filename="${filename || 'export'}.doc"`,
        },
      });
    }

    if (format === 'pdf') {
      const tableRows = data.map((row: any) =>
        `<tr>${columns.map((c: any) => {
          const val = row[c.key];
          const isAmount = c.key.includes('amount') || c.key === 'salary' || c.key === 'total';
          return `<td style="border-bottom: 1px solid #eee; padding: 6px 8px; font-size: 10px; ${isAmount ? 'text-align: right;' : ''}">${isAmount ? fmtUSD(val) : fmtVal(val)}</td>`;
        }).join('')}</tr>`
      ).join('\n');
      const thead = columns.map((c: any) => {
        const isAmount = c.key.includes('amount') || c.key === 'salary' || c.key === 'total';
        return `<th style="background: #1e3a5f; color: #fff; padding: 8px; font-size: 10px; font-weight: 600; text-align: ${isAmount ? 'right' : 'left'};">${c.label}</th>`;
      }).join('');
      const company = await withTenantContext(session.tenant_id, () => get('SELECT * FROM company_settings')) as any;
      const cName = company?.company_name || 'BiasharaLedger';
      const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${title || 'Report'}</title>
        <style>body{font-family:'Helvetica Neue',Arial;padding:20px;color:#333;font-size:11px;}
        table{width:100%;border-collapse:collapse;margin-top:12px;}
        th:first-child,td:first-child{padding-left:0;}
        th:last-child,td:last-child{padding-right:0;}
        .footer{text-align:center;font-size:9px;color:#aaa;border-top:1px solid #eee;padding-top:10px;margin-top:20px;}
        </style></head><body>
        <div style="border-bottom:2px solid #1e3a5f;padding-bottom:8px;margin-bottom:16px;">
          <div style="font-size:16px;font-weight:700;color:#1e3a5f;">${cName}</div>
          <div style="font-size:18px;font-weight:700;color:#333;margin-top:4px;">${title || 'Report'}</div>
        </div>
        <table>${thead ? `<thead><tr>${thead}</tr></thead>` : ''}<tbody>${tableRows || '<tr><td style="padding:20px;text-align:center;color:#999;">No data</td></tr>'}</tbody></table>
        <div class="footer">Generated by BiasharaLedger &bull; ${new Date().toLocaleDateString('en-US')}</div>
      </body></html>`;
      let puppeteer: any;
      try {
        puppeteer = await import('puppeteer').then(m => m.default);
      } catch {
        return NextResponse.json({ error: 'PDF generation is not available' }, { status: 500 });
      }
      const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
      });
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'load' });
      const pdfBuffer = await page.pdf({ format: 'A4', margin: { top: '10mm', bottom: '10mm', left: '8mm', right: '8mm' }, printBackground: true });
      await browser.close();
      return new NextResponse(Buffer.from(pdfBuffer), {
        status: 200,
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="${filename || 'export'}.pdf"`,
        },
      });
    }

    return NextResponse.json({ error: 'Unsupported format' }, { status: 400 });
  } catch (err: any) {
    console.error('Export error:', err);
    return NextResponse.json({ error: 'Export failed. Please try again.' }, { status: 500 });
  }
}
