export type IndustryPreset = {
  categories: { name: string; children?: { name: string }[] }[];
  customFields: { name: string; type: string; options?: string[] }[];
  uoms: string[];
};

export type CatalogProduct = {
  name: string;
  default_uom: string;
  category: string;
};

export type CatalogCategory = {
  category: string;
  products: CatalogProduct[];
};

const PRESETS: Record<string, IndustryPreset> = {
  agriculture: {
    categories: [
      { name: 'Seeds', children: [{ name: 'Cereals' }, { name: 'Vegetables' }, { name: 'Fruits' }] },
      { name: 'Fertilizers' },
      { name: 'Pesticides' },
      {
        name: 'Animal Feed',
        children: [
          { name: 'Dairy Meal' }, { name: 'Layer Mash' }, { name: 'Broiler Feed' },
          { name: 'Pig Feed' }, { name: 'Fish Feed' }, { name: 'Dog Food' },
          { name: 'Mineral Supplements' }, { name: 'Hay & Forage' },
        ],
      },
      { name: 'Farm Tools' },
    ],
    customFields: [
      { name: 'Brand', type: 'text' },
      { name: 'Variety', type: 'text' },
      { name: 'Supplier', type: 'text' },
      { name: 'Harvest Date', type: 'date' },
    ],
    uoms: ['kg', 'g', 'ton', 'l', 'ml', 'bag', 'sack', 'pcs', 'acre'],
  },
  retail: {
    categories: [
      { name: 'Electronics', children: [{ name: 'Phones' }, { name: 'Laptops' }, { name: 'Accessories' }] },
      { name: 'Clothing', children: [{ name: 'Men' }, { name: 'Women' }, { name: 'Children' }] },
      { name: 'Food & Beverages' },
      { name: 'Household' },
    ],
    customFields: [
      { name: 'Brand', type: 'text' },
      { name: 'Size', type: 'text' },
      { name: 'Color', type: 'text' },
      { name: 'Supplier SKU', type: 'text' },
    ],
    uoms: ['pcs', 'box', 'pack', 'dozen', 'carton', 'kg', 'l'],
  },
  manufacturing: {
    categories: [
      { name: 'Raw Materials', children: [{ name: 'Metals' }, { name: 'Plastics' }, { name: 'Chemicals' }, { name: 'Textiles' }] },
      { name: 'Work in Progress' },
      { name: 'Finished Goods' },
      { name: 'Packaging', children: [{ name: 'Boxes' }, { name: 'Labels' }, { name: 'Wrapping' }] },
      { name: 'Spare Parts' },
    ],
    customFields: [
      { name: 'Grade', type: 'text' },
      { name: 'Specification', type: 'text' },
      { name: 'Supplier', type: 'text' },
      { name: 'Batch Number', type: 'text' },
      { name: 'Lead Time (days)', type: 'number' },
    ],
    uoms: ['kg', 'g', 'ton', 'l', 'ml', 'm', 'cm', 'roll', 'sheet', 'pcs', 'pallet'],
  },
  construction: {
    categories: [
      { name: 'Building Materials', children: [{ name: 'Cement' }, { name: 'Steel' }, { name: 'Timber' }, { name: 'Aggregates' }] },
      { name: 'Plumbing', children: [{ name: 'Pipes' }, { name: 'Fittings' }, { name: 'Valves' }] },
      { name: 'Electrical', children: [{ name: 'Cables' }, { name: 'Switches' }, { name: 'Lighting' }] },
      { name: 'Tools & Equipment' },
      { name: 'Safety Gear' },
    ],
    customFields: [
      { name: 'Grade', type: 'text' },
      { name: 'Specification', type: 'text' },
      { name: 'Supplier', type: 'text' },
      { name: 'Certification', type: 'text' },
    ],
    uoms: ['kg', 'ton', 'm', 'cm', 'pcs', 'bag', 'roll', 'sheet', 'l'],
  },
  hospital: {
    categories: [
      { name: 'Medicines', children: [{ name: 'Tablets' }, { name: 'Injections' }, { name: 'Syrups' }, { name: 'Topical' }] },
      { name: 'Consumables', children: [{ name: 'Gloves' }, { name: 'Syringes' }, { name: 'Bandages' }, { name: 'Masks' }] },
      { name: 'Equipment', children: [{ name: 'Diagnostic' }, { name: 'Surgical' }, { name: 'Monitoring' }] },
      { name: 'Laboratory' },
      { name: 'Furniture' },
    ],
    customFields: [
      { name: 'Batch Number', type: 'text' },
      { name: 'Expiry Date', type: 'date' },
      { name: 'Manufacturer', type: 'text' },
      { name: 'Storage Temp (°C)', type: 'text' },
      { name: 'Dosage', type: 'text' },
    ],
    uoms: ['pcs', 'box', 'strip', 'bottle', 'vial', 'ampoule', 'pack', 'carton', 'l', 'ml'],
  },
  general: {
    categories: [
      { name: 'Office Supplies' },
      { name: 'Equipment' },
      { name: 'Merchandise' },
      { name: 'Packaging' },
      { name: 'Other' },
    ],
    customFields: [],
    uoms: ['pcs', 'kg', 'l', 'box', 'pack', 'dozen'],
  },
};

const CATALOG: Record<string, CatalogCategory[]> = {
  agriculture: [
    {
      category: 'Dairy Feeds',
      products: [
        { name: 'Dairy Meal 16%', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Dairy Meal 18%', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Dairy Meal 20%', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Dairy Meal 22%', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Calf Starter Pellets', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Calf Rearing Pellets', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Dairy Concentrates 16%', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Dairy Concentrates 20%', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Dairy Premix 5%', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Dairy Premix 2.5%', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Lactating Cow Meal', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Dry Cow Meal', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Heifer Rearing Meal', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Dairy Yeast Culture', default_uom: 'kg', category: 'Animal Feed' },
      ],
    },
    {
      category: 'Poultry Feeds - Layers',
      products: [
        { name: 'Chick Mash (0-8 wks)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Chick Crumbs (0-8 wks)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Growers Mash (9-18 wks)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Growers Pellets (9-18 wks)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Layer Mash (19+ wks)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Layer Pellets (19+ wks)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Layer Crumbs (19+ wks)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Layer Concentrates', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Layer Premix 2.5%', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Layer Premix 5%', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Point of Lay Mash', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Organic Layer Mash', default_uom: 'kg', category: 'Animal Feed' },
      ],
    },
    {
      category: 'Poultry Feeds - Broilers',
      products: [
        { name: 'Broiler Starter (0-4 wks)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Broiler Starter Crumbs', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Broiler Finisher (4+ wks)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Broiler Finisher Pellets', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Broiler Concentrates', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Broiler Premix 2.5%', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Broiler Premix 5%', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Broiler Grower (dual-purpose)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Organic Broiler Feed', default_uom: 'kg', category: 'Animal Feed' },
      ],
    },
    {
      category: 'Poultry Feeds - Other',
      products: [
        { name: 'Turkey Starter', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Turkey Grower', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Turkey Finisher', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Duck Feed Starter', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Duck Feed Grower', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Duck Feed Layer', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Geese Feed', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Ostrich Starter', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Ostrich Grower', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Ostrich Finisher', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Guinea Fowl Starter', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Guinea Fowl Grower', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Quail Feed Starter', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Quail Feed Layer', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Pigeon Feed Mix', default_uom: 'kg', category: 'Animal Feed' },
      ],
    },
    {
      category: 'Pig Feeds',
      products: [
        { name: 'Pig Starter / Weaner (0-30kg)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Pig Grower (30-60kg)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Pig Finisher (60-100kg)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Lactating Sow Feed', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Gestating Sow Feed', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Boar Feed', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Pig Concentrates', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Pig Premix 2.5%', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Pig Premix 5%', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Piglet Creep Feed', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Organic Pig Feed', default_uom: 'kg', category: 'Animal Feed' },
      ],
    },
    {
      category: 'Fish Feeds',
      products: [
        { name: 'Fry Feed (0.5-1mm)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Fingerling Feed (1-2mm)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Grower Feed (2-3mm)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Grower Feed (3-4mm)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Finisher Feed (4-5mm)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Finisher Feed (6mm)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Floating Fish Pellets 2mm', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Floating Fish Pellets 3mm', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Floating Fish Pellets 4.5mm', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Floating Fish Pellets 6mm', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Sinking Fish Pellets 2mm', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Sinking Fish Pellets 3mm', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Sinking Fish Pellets 4mm', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Sinking Fish Pellets 6mm', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Tilapia Feed Starter', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Tilapia Feed Grower', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Tilapia Feed Finisher', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Trout Feed Starter', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Trout Feed Grower', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Trout Feed Finisher', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Catfish Feed Starter', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Catfish Feed Grower', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Catfish Feed Finisher', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Fish Premix', default_uom: 'kg', category: 'Animal Feed' },
      ],
    },
    {
      category: 'Sheep & Goat Feeds',
      products: [
        { name: 'Sheep Finisher Pellets', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Sheep Grower Meal', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Goat Finisher Pellets', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Goat Grower Meal', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Lactating Doe/Sheep Feed', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Sheep & Goat Concentrates', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Sheep & Goat Premix', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Organic Goat Feed', default_uom: 'kg', category: 'Animal Feed' },
      ],
    },
    {
      category: 'Rabbit Feeds',
      products: [
        { name: 'Rabbit Starter Pellets', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Rabbit Grower Pellets', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Rabbit Finisher Pellets', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Lactating Doe Feed', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Rabbit Concentrates', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Rabbit Premix', default_uom: 'kg', category: 'Animal Feed' },
      ],
    },
    {
      category: 'Horse & Donkey Feeds',
      products: [
        { name: 'Horse Cubes', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Horse Mix (Sweet Feed)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Horse Pellets', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Performance Horse Feed', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Broodmare Feed', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Foal Starter', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Donkey Feed Pellets', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Donkey Mineral Mix', default_uom: 'kg', category: 'Animal Feed' },
      ],
    },
    {
      category: 'Camel Feeds',
      products: [
        { name: 'Camel Grower Pellets', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Lactating Camel Feed', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Camel Mineral Blocks', default_uom: 'pcs', category: 'Animal Feed' },
        { name: 'Camel Concentrates', default_uom: 'kg', category: 'Animal Feed' },
      ],
    },
    {
      category: 'Hay & Forage',
      products: [
        { name: 'Alfalfa Hay (Bale)', default_uom: 'pcs', category: 'Animal Feed' },
        { name: 'Alfalfa Hay (Chopped)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Timothy Hay (Bale)', default_uom: 'pcs', category: 'Animal Feed' },
        { name: 'Timothy Hay (Chopped)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Bermuda Grass Hay (Bale)', default_uom: 'pcs', category: 'Animal Feed' },
        { name: 'Bermuda Grass Hay (Chopped)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Oat Hay (Bale)', default_uom: 'pcs', category: 'Animal Feed' },
        { name: 'Oat Hay (Chopped)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Barley Hay (Bale)', default_uom: 'pcs', category: 'Animal Feed' },
        { name: 'Barley Hay (Chopped)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Lucerne Hay (Bale)', default_uom: 'pcs', category: 'Animal Feed' },
        { name: 'Lucerne Hay (Chopped)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Grass Silage (Bale)', default_uom: 'pcs', category: 'Animal Feed' },
        { name: 'Grass Silage (Bulk)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Maize Silage (Bale)', default_uom: 'pcs', category: 'Animal Feed' },
        { name: 'Maize Silage (Bulk)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Wheat Straw (Bale)', default_uom: 'pcs', category: 'Animal Feed' },
        { name: 'Barley Straw (Bale)', default_uom: 'pcs', category: 'Animal Feed' },
        { name: 'Pasture Hay Mix (Bale)', default_uom: 'pcs', category: 'Animal Feed' },
        { name: 'Pasture Hay Mix (Chopped)', default_uom: 'kg', category: 'Animal Feed' },
      ],
    },
    {
      category: 'Mineral Supplements & Licks',
      products: [
        { name: 'Cattle Molasses Lick Block', default_uom: 'pcs', category: 'Animal Feed' },
        { name: 'Cattle Mineral Lick Block', default_uom: 'pcs', category: 'Animal Feed' },
        { name: 'Dairy Cow Mineral Powder', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Sheep Mineral Lick Block', default_uom: 'pcs', category: 'Animal Feed' },
        { name: 'Goat Mineral Lick Block', default_uom: 'pcs', category: 'Animal Feed' },
        { name: 'Poultry Grit (Flint)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Poultry Grit (Oyster Shell)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Salt Block (White)', default_uom: 'pcs', category: 'Animal Feed' },
        { name: 'Salt Block (Brown)', default_uom: 'pcs', category: 'Animal Feed' },
        { name: 'Feed Grade Limestone Powder', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Dicalcium Phosphate (DCP)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Monocalcium Phosphate (MCP)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Feed Grade Salt (NaCl)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Sodium Bicarbonate (Buffer)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Magnesium Oxide', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Feed Grade Urea', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Molasses (Cane)', default_uom: 'l', category: 'Animal Feed' },
        { name: 'Molasses (Beet)', default_uom: 'l', category: 'Animal Feed' },
      ],
    },
    {
      category: 'Feed Ingredients & Raw Materials',
      products: [
        { name: 'Maize Grain', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Maize Germ Meal', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Maize Bran', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Maize Gluten Meal', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Wheat Pollard', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Wheat Bran', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Soybean Meal 44%', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Soybean Meal 48%', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Full Fat Soya (Extruded)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Sunflower Seed Cake', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Cotton Seed Cake', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Canola Meal', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Fishmeal 60%', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Fishmeal 65%', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Meat & Bone Meal', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Blood Meal', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Feather Meal', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Rice Bran (Full Fat)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Rice Bran (Extracted)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Cassava Chips', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Cassava Peel Meal', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Coconut Oil Cake (Copra)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Palm Kernel Cake', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Sorghum Grain', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Barley Grain', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Oats Grain', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Wheat Grain', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Peas (Field Peas)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Cowpeas', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Lupins', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'DDGS (Distillers Grains)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Brewers Spent Grain (Wet)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Brewers Spent Grain (Dry)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Vegetable Oil (Palm)', default_uom: 'l', category: 'Animal Feed' },
        { name: 'Vegetable Oil (Soya)', default_uom: 'l', category: 'Animal Feed' },
        { name: 'Animal Fat (Tallow)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Poultry Fat', default_uom: 'kg', category: 'Animal Feed' },
      ],
    },
    {
      category: 'Feed Additives & Premixes',
      products: [
        { name: 'Vitamin A + D3 + E Premix', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Vitamin B-Complex Premix', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Trace Mineral Premix', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Amino Acid Premix (Lysine)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Amino Acid Premix (Methionine)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Amino Acid Premix (Threonine)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Coccidiostat Premix', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Antibiotic Growth Promoter', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Enzyme Premix (Phytase)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Enzyme Premix (Xylanase)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Probiotic Premix', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Mycotoxin Binder', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Feed Antioxidant (BHT)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Feed Flavor (Sweetener)', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Pellet Binder', default_uom: 'kg', category: 'Animal Feed' },
        { name: 'Mold Inhibitor', default_uom: 'kg', category: 'Animal Feed' },
      ],
    },
    {
      category: 'Seeds',
      products: [
        { name: 'Maize Seed (Hybrid)', default_uom: 'kg', category: 'Seeds' },
        { name: 'Wheat Seed', default_uom: 'kg', category: 'Seeds' },
        { name: 'Barley Seed', default_uom: 'kg', category: 'Seeds' },
        { name: 'Sorghum Seed', default_uom: 'kg', category: 'Seeds' },
        { name: 'Beans Seed', default_uom: 'kg', category: 'Seeds' },
        { name: 'Cowpea Seed', default_uom: 'kg', category: 'Seeds' },
        { name: 'Soybean Seed', default_uom: 'kg', category: 'Seeds' },
        { name: 'Sunflower Seed', default_uom: 'kg', category: 'Seeds' },
        { name: 'Tomato Seed', default_uom: 'pcs', category: 'Seeds' },
        { name: 'Cabbage Seed', default_uom: 'pcs', category: 'Seeds' },
        { name: 'Kale Seed (Sukuma Wiki)', default_uom: 'pcs', category: 'Seeds' },
        { name: 'Spinach Seed', default_uom: 'pcs', category: 'Seeds' },
        { name: 'Onion Seed', default_uom: 'pcs', category: 'Seeds' },
        { name: 'Carrot Seed', default_uom: 'pcs', category: 'Seeds' },
        { name: 'French Bean Seed', default_uom: 'kg', category: 'Seeds' },
        { name: 'Watermelon Seed', default_uom: 'pcs', category: 'Seeds' },
        { name: 'Capsicum Seed', default_uom: 'pcs', category: 'Seeds' },
        { name: 'Coriander Seed', default_uom: 'pcs', category: 'Seeds' },
      ],
    },
    {
      category: 'Fertilizers',
      products: [
        { name: 'NPK 23:23:0', default_uom: 'kg', category: 'Fertilizers' },
        { name: 'NPK 10:10:10', default_uom: 'kg', category: 'Fertilizers' },
        { name: 'NPK 17:17:17', default_uom: 'kg', category: 'Fertilizers' },
        { name: 'CAN (Calcium Ammonium Nitrate)', default_uom: 'kg', category: 'Fertilizers' },
        { name: 'Urea 46% N', default_uom: 'kg', category: 'Fertilizers' },
        { name: 'DAP (Diammonium Phosphate)', default_uom: 'kg', category: 'Fertilizers' },
        { name: 'SSP (Single Superphosphate)', default_uom: 'kg', category: 'Fertilizers' },
        { name: 'MOP (Muriate of Potash)', default_uom: 'kg', category: 'Fertilizers' },
        { name: 'Organic Compost', default_uom: 'kg', category: 'Fertilizers' },
        { name: 'Manure (Cow)', default_uom: 'kg', category: 'Fertilizers' },
        { name: 'Manure (Chicken)', default_uom: 'kg', category: 'Fertilizers' },
        { name: 'Foliar Feed (Liquid)', default_uom: 'l', category: 'Fertilizers' },
        { name: 'Magnesium Sulphate', default_uom: 'kg', category: 'Fertilizers' },
        { name: 'Zinc Sulphate', default_uom: 'kg', category: 'Fertilizers' },
      ],
    },
    {
      category: 'Pesticides & Herbicides',
      products: [
        { name: 'Glyphosate (Roundup)', default_uom: 'l', category: 'Pesticides' },
        { name: '2,4-D Amine', default_uom: 'l', category: 'Pesticides' },
        { name: 'Atrazine', default_uom: 'l', category: 'Pesticides' },
        { name: 'Paraquat', default_uom: 'l', category: 'Pesticides' },
        { name: 'Cypermethrin', default_uom: 'l', category: 'Pesticides' },
        { name: 'Lambda-cyhalothrin', default_uom: 'l', category: 'Pesticides' },
        { name: 'Imidacloprid', default_uom: 'l', category: 'Pesticides' },
        { name: 'Mancozeb', default_uom: 'kg', category: 'Pesticides' },
        { name: 'Copper Oxychloride', default_uom: 'kg', category: 'Pesticides' },
        { name: 'Sulphur (Wettable)', default_uom: 'kg', category: 'Pesticides' },
        { name: 'Fungicide Spray (General)', default_uom: 'l', category: 'Pesticides' },
      ],
    },
    {
      category: 'Farm Tools & Equipment',
      products: [
        { name: 'Jembe (Hoe)', default_uom: 'pcs', category: 'Farm Tools' },
        { name: 'Panga (Machete)', default_uom: 'pcs', category: 'Farm Tools' },
        { name: 'Forked Jembe', default_uom: 'pcs', category: 'Farm Tools' },
        { name: 'Slasher', default_uom: 'pcs', category: 'Farm Tools' },
        { name: 'Wheelbarrow', default_uom: 'pcs', category: 'Farm Tools' },
        { name: 'Watering Can', default_uom: 'pcs', category: 'Farm Tools' },
        { name: 'Spray Pump (Knapsack)', default_uom: 'pcs', category: 'Farm Tools' },
        { name: 'Secateurs (Pruning Shears)', default_uom: 'pcs', category: 'Farm Tools' },
        { name: 'Garden Fork', default_uom: 'pcs', category: 'Farm Tools' },
        { name: 'Rake', default_uom: 'pcs', category: 'Farm Tools' },
        { name: 'Spade', default_uom: 'pcs', category: 'Farm Tools' },
        { name: 'Measuring Tape (50m)', default_uom: 'pcs', category: 'Farm Tools' },
      ],
    },
  ],
  retail: [
    {
      category: 'Electronics',
      products: [
        { name: 'Smartphone', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Feature Phone', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Laptop', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Desktop Computer', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Tablet', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Smartwatch', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Bluetooth Headphones', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Wired Headphones', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Bluetooth Speaker', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Phone Charger', default_uom: 'pcs', category: 'Electronics' },
        { name: 'USB Cable', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Power Bank', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Memory Card (SD)', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Screen Protector', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Phone Case', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Keyboard', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Mouse', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Monitor', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Printer', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Router', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Extension Cable', default_uom: 'pcs', category: 'Electronics' },
        { name: 'SIM Card', default_uom: 'pcs', category: 'Electronics' },
        { name: 'Airtime Voucher', default_uom: 'pcs', category: 'Electronics' },
      ],
    },
    {
      category: 'Clothing',
      products: [
        { name: "Men's T-Shirt", default_uom: 'pcs', category: 'Clothing' },
        { name: "Men's Shirt", default_uom: 'pcs', category: 'Clothing' },
        { name: "Men's Trousers", default_uom: 'pcs', category: 'Clothing' },
        { name: "Men's Jacket", default_uom: 'pcs', category: 'Clothing' },
        { name: "Men's Suit", default_uom: 'pcs', category: 'Clothing' },
        { name: "Women's Dress", default_uom: 'pcs', category: 'Clothing' },
        { name: "Women's Blouse", default_uom: 'pcs', category: 'Clothing' },
        { name: "Women's Skirt", default_uom: 'pcs', category: 'Clothing' },
        { name: "Women's Trousers", default_uom: 'pcs', category: 'Clothing' },
        { name: "Women's Jacket", default_uom: 'pcs', category: 'Clothing' },
        { name: "Children's Top", default_uom: 'pcs', category: 'Clothing' },
        { name: "Children's Trousers", default_uom: 'pcs', category: 'Clothing' },
        { name: "Children's Dress", default_uom: 'pcs', category: 'Clothing' },
        { name: 'Baby Onesie', default_uom: 'pcs', category: 'Clothing' },
        { name: 'Socks (Pair)', default_uom: 'pair', category: 'Clothing' },
        { name: 'Underwear', default_uom: 'pcs', category: 'Clothing' },
        { name: 'Belt', default_uom: 'pcs', category: 'Clothing' },
        { name: 'Cap / Hat', default_uom: 'pcs', category: 'Clothing' },
        { name: 'Scarf', default_uom: 'pcs', category: 'Clothing' },
        { name: 'Traditional Wear (Kitenge)', default_uom: 'pcs', category: 'Clothing' },
      ],
    },
    {
      category: 'Food & Beverages',
      products: [
        { name: 'Maize Flour (2kg)', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Maize Flour (5kg)', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Rice (1kg)', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Rice (5kg)', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Wheat Flour (2kg)', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Sugar (1kg)', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Cooking Oil (1l)', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Cooking Oil (5l)', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Bottled Water (500ml)', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Bottled Water (1l)', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Soda (Can)', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Soda (Bottle)', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Juice (500ml)', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Milk (Fresh 500ml)', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Milk (Fresh 1l)', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Yogurt', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Bread (Loaf)', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Tea Bags (100pk)', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Instant Coffee (200g)', default_uom: 'pcs', category: 'Food & Beverages' },
        { name: 'Salt (1kg)', default_uom: 'pcs', category: 'Food & Beverages' },
      ],
    },
  ],
  manufacturing: [
    {
      category: 'Raw Materials',
      products: [
        { name: 'Steel Sheet (2mm)', default_uom: 'sheet', category: 'Raw Materials' },
        { name: 'Steel Sheet (3mm)', default_uom: 'sheet', category: 'Raw Materials' },
        { name: 'Aluminium Ingot', default_uom: 'kg', category: 'Raw Materials' },
        { name: 'Copper Wire (1.5mm)', default_uom: 'm', category: 'Raw Materials' },
        { name: 'Copper Wire (2.5mm)', default_uom: 'm', category: 'Raw Materials' },
        { name: 'PVC Granules', default_uom: 'kg', category: 'Raw Materials' },
        { name: 'Polypropylene Granules', default_uom: 'kg', category: 'Raw Materials' },
        { name: 'Industrial Chemical (Acid)', default_uom: 'l', category: 'Raw Materials' },
        { name: 'Industrial Chemical (Solvent)', default_uom: 'l', category: 'Raw Materials' },
        { name: 'Cotton Fabric (Roll)', default_uom: 'roll', category: 'Raw Materials' },
        { name: 'Polyester Fabric (Roll)', default_uom: 'roll', category: 'Raw Materials' },
        { name: 'Timber (Pine)', default_uom: 'pcs', category: 'Raw Materials' },
        { name: 'Timber (Hardwood)', default_uom: 'pcs', category: 'Raw Materials' },
        { name: 'Paint Pigment Powder', default_uom: 'kg', category: 'Raw Materials' },
      ],
    },
    {
      category: 'Packaging',
      products: [
        { name: 'Corrugated Box (Small)', default_uom: 'pcs', category: 'Packaging' },
        { name: 'Corrugated Box (Medium)', default_uom: 'pcs', category: 'Packaging' },
        { name: 'Corrugated Box (Large)', default_uom: 'pcs', category: 'Packaging' },
        { name: 'Plastic Bottle (500ml)', default_uom: 'pcs', category: 'Packaging' },
        { name: 'Plastic Bottle (1l)', default_uom: 'pcs', category: 'Packaging' },
        { name: 'Glass Jar (500ml)', default_uom: 'pcs', category: 'Packaging' },
        { name: 'Label (Sticker)', default_uom: 'pcs', category: 'Packaging' },
        { name: 'Shrink Wrap (Roll)', default_uom: 'roll', category: 'Packaging' },
        { name: 'Adhesive Tape (Roll)', default_uom: 'roll', category: 'Packaging' },
        { name: 'Polybag (Small)', default_uom: 'pcs', category: 'Packaging' },
        { name: 'Polybag (Large)', default_uom: 'pcs', category: 'Packaging' },
      ],
    },
    {
      category: 'Finished Goods',
      products: [
        { name: 'Finished Product A', default_uom: 'pcs', category: 'Finished Goods' },
        { name: 'Finished Product B', default_uom: 'pcs', category: 'Finished Goods' },
        { name: 'Finished Product C', default_uom: 'pcs', category: 'Finished Goods' },
      ],
    },
    {
      category: 'Spare Parts',
      products: [
        { name: 'Bearing (SKF)', default_uom: 'pcs', category: 'Spare Parts' },
        { name: 'Bearing (NSK)', default_uom: 'pcs', category: 'Spare Parts' },
        { name: 'Belt (V-Belt A-Type)', default_uom: 'pcs', category: 'Spare Parts' },
        { name: 'Belt (V-Belt B-Type)', default_uom: 'pcs', category: 'Spare Parts' },
        { name: 'Gearbox', default_uom: 'pcs', category: 'Spare Parts' },
        { name: 'Motor (Electric 5HP)', default_uom: 'pcs', category: 'Spare Parts' },
        { name: 'Motor (Electric 10HP)', default_uom: 'pcs', category: 'Spare Parts' },
        { name: 'Hydraulic Hose', default_uom: 'm', category: 'Spare Parts' },
        { name: 'Pneumatic Fitting', default_uom: 'pcs', category: 'Spare Parts' },
        { name: 'Oil Seal', default_uom: 'pcs', category: 'Spare Parts' },
        { name: 'O-Ring', default_uom: 'pcs', category: 'Spare Parts' },
        { name: 'Filter Element (Oil)', default_uom: 'pcs', category: 'Spare Parts' },
        { name: 'Filter Element (Air)', default_uom: 'pcs', category: 'Spare Parts' },
      ],
    },
  ],
  construction: [
    {
      category: 'Building Materials',
      products: [
        { name: 'Cement (Portland 42.5N)', default_uom: 'bag', category: 'Cement' },
        { name: 'Cement (Portland 52.5N)', default_uom: 'bag', category: 'Cement' },
        { name: 'Cement (Quick Setting)', default_uom: 'bag', category: 'Cement' },
        { name: 'Reinforcing Steel Bar (Y12)', default_uom: 'pcs', category: 'Steel' },
        { name: 'Reinforcing Steel Bar (Y16)', default_uom: 'pcs', category: 'Steel' },
        { name: 'Reinforcing Steel Bar (Y20)', default_uom: 'pcs', category: 'Steel' },
        { name: 'Steel Mesh (6mm)', default_uom: 'sheet', category: 'Steel' },
        { name: 'Steel Mesh (8mm)', default_uom: 'sheet', category: 'Steel' },
        { name: 'Bricks (Clay)', default_uom: 'pcs', category: 'Aggregates' },
        { name: 'Bricks (Concrete)', default_uom: 'pcs', category: 'Aggregates' },
        { name: 'Building Stone (Machine Cut)', default_uom: 'pcs', category: 'Aggregates' },
        { name: 'Sand (Building)', default_uom: 'ton', category: 'Aggregates' },
        { name: 'Ballast (3/4")', default_uom: 'ton', category: 'Aggregates' },
        { name: 'Ballast (1/2")', default_uom: 'ton', category: 'Aggregates' },
        { name: 'Timber (2x2)', default_uom: 'pcs', category: 'Timber' },
        { name: 'Timber (2x4)', default_uom: 'pcs', category: 'Timber' },
        { name: 'Timber (4x4)', default_uom: 'pcs', category: 'Timber' },
        { name: 'Plywood (4x8)', default_uom: 'sheet', category: 'Timber' },
        { name: 'Gypsum Ceiling Board', default_uom: 'sheet', category: 'Timber' },
        { name: 'Roofing Tiles (Clay)', default_uom: 'pcs', category: 'Roofing' },
        { name: 'Roofing Sheets (Iron)', default_uom: 'sheet', category: 'Roofing' },
        { name: 'Roofing Sheets (Polycarbonate)', default_uom: 'sheet', category: 'Roofing' },
        { name: 'Nails (2")', default_uom: 'kg', category: 'Hardware' },
        { name: 'Nails (3")', default_uom: 'kg', category: 'Hardware' },
        { name: 'Nails (4")', default_uom: 'kg', category: 'Hardware' },
      ],
    },
    {
      category: 'Plumbing',
      products: [
        { name: 'PVC Pipe (1/2")', default_uom: 'pcs', category: 'Pipes' },
        { name: 'PVC Pipe (1")', default_uom: 'pcs', category: 'Pipes' },
        { name: 'PVC Pipe (2")', default_uom: 'pcs', category: 'Pipes' },
        { name: 'Galvanized Pipe (1/2")', default_uom: 'pcs', category: 'Pipes' },
        { name: 'Galvanized Pipe (1")', default_uom: 'pcs', category: 'Pipes' },
        { name: 'PVC Elbow (1/2")', default_uom: 'pcs', category: 'Fittings' },
        { name: 'PVC Elbow (1")', default_uom: 'pcs', category: 'Fittings' },
        { name: 'PVC Elbow (2")', default_uom: 'pcs', category: 'Fittings' },
        { name: 'PVC Tee (1/2")', default_uom: 'pcs', category: 'Fittings' },
        { name: 'PVC Tee (1")', default_uom: 'pcs', category: 'Fittings' },
        { name: 'Ball Valve (1/2")', default_uom: 'pcs', category: 'Valves' },
        { name: 'Ball Valve (1")', default_uom: 'pcs', category: 'Valves' },
        { name: 'Gate Valve (1/2")', default_uom: 'pcs', category: 'Valves' },
        { name: 'Water Meter', default_uom: 'pcs', category: 'Valves' },
        { name: 'Tap (Basin)', default_uom: 'pcs', category: 'Fittings' },
        { name: 'Tap (Kitchen)', default_uom: 'pcs', category: 'Fittings' },
        { name: 'Flush Toilet Cistern', default_uom: 'pcs', category: 'Fittings' },
        { name: 'Wash Basin', default_uom: 'pcs', category: 'Fittings' },
      ],
    },
    {
      category: 'Electrical',
      products: [
        { name: 'Electrical Cable (1.5mm2)', default_uom: 'm', category: 'Cables' },
        { name: 'Electrical Cable (2.5mm2)', default_uom: 'm', category: 'Cables' },
        { name: 'Electrical Cable (4mm2)', default_uom: 'm', category: 'Cables' },
        { name: 'Electrical Cable (6mm2)', default_uom: 'm', category: 'Cables' },
        { name: 'Armoured Cable (10mm2)', default_uom: 'm', category: 'Cables' },
        { name: 'Switch (Single)', default_uom: 'pcs', category: 'Switches' },
        { name: 'Switch (Double)', default_uom: 'pcs', category: 'Switches' },
        { name: 'Socket (Single)', default_uom: 'pcs', category: 'Switches' },
        { name: 'Socket (Double)', default_uom: 'pcs', category: 'Switches' },
        { name: 'MCB (Single Pole)', default_uom: 'pcs', category: 'Switches' },
        { name: 'MCB (Double Pole)', default_uom: 'pcs', category: 'Switches' },
        { name: 'LED Bulb (10W)', default_uom: 'pcs', category: 'Lighting' },
        { name: 'LED Bulb (20W)', default_uom: 'pcs', category: 'Lighting' },
        { name: 'LED Tube Light (4ft)', default_uom: 'pcs', category: 'Lighting' },
        { name: 'Flood Light (50W)', default_uom: 'pcs', category: 'Lighting' },
        { name: 'Flood Light (100W)', default_uom: 'pcs', category: 'Lighting' },
        { name: 'Distribution Board', default_uom: 'pcs', category: 'Switches' },
        { name: 'Electric Meter (Single Phase)', default_uom: 'pcs', category: 'Switches' },
      ],
    },
    {
      category: 'Tools & Safety',
      products: [
        { name: 'Safety Helmet', default_uom: 'pcs', category: 'Safety Gear' },
        { name: 'Safety Vest (Reflective)', default_uom: 'pcs', category: 'Safety Gear' },
        { name: 'Safety Boots (Steel Toe)', default_uom: 'pair', category: 'Safety Gear' },
        { name: 'Safety Goggles', default_uom: 'pcs', category: 'Safety Gear' },
        { name: 'Dust Mask', default_uom: 'pcs', category: 'Safety Gear' },
        { name: 'Work Gloves (Leather)', default_uom: 'pair', category: 'Safety Gear' },
        { name: 'Concrete Mixer', default_uom: 'pcs', category: 'Tools' },
        { name: 'Wheelbarrow (Heavy Duty)', default_uom: 'pcs', category: 'Tools' },
        { name: 'Measuring Tape (5m)', default_uom: 'pcs', category: 'Tools' },
        { name: 'Spirit Level', default_uom: 'pcs', category: 'Tools' },
        { name: 'Trowel', default_uom: 'pcs', category: 'Tools' },
        { name: 'Pick Axe', default_uom: 'pcs', category: 'Tools' },
        { name: 'Shovel', default_uom: 'pcs', category: 'Tools' },
      ],
    },
  ],
  hospital: [
    {
      category: 'Medicines - Tablets',
      products: [
        { name: 'Paracetamol (500mg)', default_uom: 'strip', category: 'Medicines' },
        { name: 'Amoxicillin (500mg)', default_uom: 'strip', category: 'Medicines' },
        { name: 'Ibuprofen (400mg)', default_uom: 'strip', category: 'Medicines' },
        { name: 'Metformin (500mg)', default_uom: 'strip', category: 'Medicines' },
        { name: 'Aspirin (75mg)', default_uom: 'strip', category: 'Medicines' },
        { name: 'Omeprazole (20mg)', default_uom: 'strip', category: 'Medicines' },
        { name: 'Lisinopril (10mg)', default_uom: 'strip', category: 'Medicines' },
        { name: 'Amlodipine (5mg)', default_uom: 'strip', category: 'Medicines' },
        { name: 'Cetirizine (10mg)', default_uom: 'strip', category: 'Medicines' },
        { name: 'Ciprofloxacin (500mg)', default_uom: 'strip', category: 'Medicines' },
        { name: 'Doxycycline (100mg)', default_uom: 'strip', category: 'Medicines' },
        { name: 'Diclofenac (50mg)', default_uom: 'strip', category: 'Medicines' },
        { name: 'Prednisolone (5mg)', default_uom: 'strip', category: 'Medicines' },
        { name: 'Warfarin (5mg)', default_uom: 'strip', category: 'Medicines' },
        { name: 'Oral Contraceptive Pill', default_uom: 'strip', category: 'Medicines' },
        { name: 'Vitamin B Complex', default_uom: 'strip', category: 'Medicines' },
        { name: 'Vitamin C (1000mg)', default_uom: 'strip', category: 'Medicines' },
        { name: 'Iron Supplement (Ferrous)', default_uom: 'strip', category: 'Medicines' },
        { name: 'Multivitamin Tablets', default_uom: 'bottle', category: 'Medicines' },
      ],
    },
    {
      category: 'Medicines - Injections',
      products: [
        { name: 'Ceftriaxone (1g Inj)', default_uom: 'vial', category: 'Medicines' },
        { name: 'Penicillin G (5MU Inj)', default_uom: 'vial', category: 'Medicines' },
        { name: 'Gentamicin (80mg Inj)', default_uom: 'ampoule', category: 'Medicines' },
        { name: 'Pethidine (50mg Inj)', default_uom: 'ampoule', category: 'Medicines' },
        { name: 'Insulin (Rapid Acting)', default_uom: 'vial', category: 'Medicines' },
        { name: 'Insulin (Long Acting)', default_uom: 'vial', category: 'Medicines' },
        { name: 'IV Fluids (Normal Saline 1l)', default_uom: 'pcs', category: 'Medicines' },
        { name: "IV Fluids (Ringer's Lactate 1l)", default_uom: 'pcs', category: 'Medicines' },
        { name: 'Vitamin B12 Inj', default_uom: 'ampoule', category: 'Medicines' },
        { name: 'Dexamethasone (4mg Inj)', default_uom: 'ampoule', category: 'Medicines' },
      ],
    },
    {
      category: 'Medicines - Syrups & Topical',
      products: [
        { name: 'Amoxicillin Syrup (125mg/5ml)', default_uom: 'bottle', category: 'Medicines' },
        { name: 'Paracetamol Syrup (120mg/5ml)', default_uom: 'bottle', category: 'Medicines' },
        { name: 'Cough Syrup (Guaifenesin)', default_uom: 'bottle', category: 'Medicines' },
        { name: 'Ibuprofen Syrup (100mg/5ml)', default_uom: 'bottle', category: 'Medicines' },
        { name: 'Antacid Suspension', default_uom: 'bottle', category: 'Medicines' },
        { name: 'ORS Sachets', default_uom: 'pcs', category: 'Medicines' },
        { name: 'Zinc Supplement Syrup', default_uom: 'bottle', category: 'Medicines' },
        { name: 'Betamethasone Cream', default_uom: 'tube', category: 'Medicines' },
        { name: 'Clotrimazole Cream', default_uom: 'tube', category: 'Medicines' },
        { name: 'Mupirocin Ointment', default_uom: 'tube', category: 'Medicines' },
        { name: 'Hydrocortisone Cream', default_uom: 'tube', category: 'Medicines' },
        { name: 'Antiseptic Solution (Savlon)', default_uom: 'bottle', category: 'Medicines' },
      ],
    },
    {
      category: 'Consumables',
      products: [
        { name: 'Surgical Gloves (Latex, Pair)', default_uom: 'pair', category: 'Consumables' },
        { name: 'Surgical Gloves (Nitrile, Pair)', default_uom: 'pair', category: 'Consumables' },
        { name: 'Examination Gloves (Box)', default_uom: 'box', category: 'Consumables' },
        { name: 'Syringe (2ml)', default_uom: 'pcs', category: 'Consumables' },
        { name: 'Syringe (5ml)', default_uom: 'pcs', category: 'Consumables' },
        { name: 'Syringe (10ml)', default_uom: 'pcs', category: 'Consumables' },
        { name: 'Needle (23G)', default_uom: 'pcs', category: 'Consumables' },
        { name: 'Needle (21G)', default_uom: 'pcs', category: 'Consumables' },
        { name: 'Cotton Wool (Roll)', default_uom: 'roll', category: 'Consumables' },
        { name: 'Gauze Bandage (4")', default_uom: 'pcs', category: 'Consumables' },
        { name: 'Gauze Bandage (6")', default_uom: 'pcs', category: 'Consumables' },
        { name: 'Adhesive Plaster (Roll)', default_uom: 'roll', category: 'Consumables' },
        { name: 'Surgical Tape (Micropore)', default_uom: 'roll', category: 'Consumables' },
        { name: 'Face Mask (Surgical)', default_uom: 'pcs', category: 'Consumables' },
        { name: 'Face Mask (N95)', default_uom: 'pcs', category: 'Consumables' },
        { name: 'Disposable Cap', default_uom: 'pcs', category: 'Consumables' },
        { name: 'Disposable Gown', default_uom: 'pcs', category: 'Consumables' },
        { name: 'Urine Bag (Drainage)', default_uom: 'pcs', category: 'Consumables' },
        { name: 'Catheter (Foley 2-way)', default_uom: 'pcs', category: 'Consumables' },
        { name: 'IV Cannula (18G)', default_uom: 'pcs', category: 'Consumables' },
        { name: 'IV Cannula (20G)', default_uom: 'pcs', category: 'Consumables' },
        { name: 'IV Drip Set', default_uom: 'pcs', category: 'Consumables' },
        { name: 'Glucose Test Strips', default_uom: 'pcs', category: 'Consumables' },
      ],
    },
    {
      category: 'Medical Equipment',
      products: [
        { name: 'Digital Thermometer', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Blood Pressure Monitor (Digital)', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Stethoscope', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Glucometer', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Pulse Oximeter', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Nebulizer', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Otoscope', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Ophthalmoscope', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Surgical Scissors', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Scalpel Handle + Blade', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Artery Forceps', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Tissue Forceps', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Needle Holder', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Suture Kit (Dissolvable)', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Suture Kit (Non-dissolvable)', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Stainless Steel Tray', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Patient Bed (Hospital)', default_uom: 'pcs', category: 'Furniture' },
        { name: 'Drip Stand', default_uom: 'pcs', category: 'Furniture' },
        { name: 'Examination Couch', default_uom: 'pcs', category: 'Furniture' },
        { name: 'Instrument Trolley', default_uom: 'pcs', category: 'Furniture' },
      ],
    },
    {
      category: 'Laboratory',
      products: [
        { name: 'Microscope Slide', default_uom: 'pcs', category: 'Laboratory' },
        { name: 'Cover Slip', default_uom: 'pcs', category: 'Laboratory' },
        { name: 'Test Tube (Glass)', default_uom: 'pcs', category: 'Laboratory' },
        { name: 'Test Tube (Plastic)', default_uom: 'pcs', category: 'Laboratory' },
        { name: 'Vacutainer (Plain)', default_uom: 'pcs', category: 'Laboratory' },
        { name: 'Vacutainer (EDTA)', default_uom: 'pcs', category: 'Laboratory' },
        { name: 'Vacutainer (Citrate)', default_uom: 'pcs', category: 'Laboratory' },
        { name: 'Specimen Container (Stool)', default_uom: 'pcs', category: 'Laboratory' },
        { name: 'Specimen Container (Urine)', default_uom: 'pcs', category: 'Laboratory' },
        { name: 'Pipette (1ml)', default_uom: 'pcs', category: 'Laboratory' },
        { name: 'Pipette (5ml)', default_uom: 'pcs', category: 'Laboratory' },
        { name: 'Petri Dish', default_uom: 'pcs', category: 'Laboratory' },
        { name: 'Urine Dipstick Strips', default_uom: 'pcs', category: 'Laboratory' },
        { name: 'RDT Test Kit (Malaria)', default_uom: 'pcs', category: 'Laboratory' },
        { name: 'RDT Test Kit (Typhoid)', default_uom: 'pcs', category: 'Laboratory' },
        { name: 'RDT Test Kit (HIV)', default_uom: 'pcs', category: 'Laboratory' },
        { name: 'Pregnancy Test Kit', default_uom: 'pcs', category: 'Laboratory' },
        { name: 'Tourniquet', default_uom: 'pcs', category: 'Laboratory' },
      ],
    },
  ],
  general: [
    {
      category: 'Office Supplies',
      products: [
        { name: 'A4 Paper (Ream)', default_uom: 'pcs', category: 'Office Supplies' },
        { name: 'A4 Paper (Carton)', default_uom: 'carton', category: 'Office Supplies' },
        { name: 'Ballpoint Pen (Blue)', default_uom: 'pcs', category: 'Office Supplies' },
        { name: 'Ballpoint Pen (Black)', default_uom: 'pcs', category: 'Office Supplies' },
        { name: 'Pencil (HB)', default_uom: 'pcs', category: 'Office Supplies' },
        { name: 'Stapler', default_uom: 'pcs', category: 'Office Supplies' },
        { name: 'Staples (Box)', default_uom: 'box', category: 'Office Supplies' },
        { name: 'Paper Clip (Box)', default_uom: 'box', category: 'Office Supplies' },
        { name: 'Sticky Notes (Pad)', default_uom: 'pcs', category: 'Office Supplies' },
        { name: 'File Folder (Manila)', default_uom: 'pcs', category: 'Office Supplies' },
        { name: 'Ring Binder', default_uom: 'pcs', category: 'Office Supplies' },
        { name: 'Correction Fluid', default_uom: 'pcs', category: 'Office Supplies' },
        { name: 'Marker (Permanent)', default_uom: 'pcs', category: 'Office Supplies' },
        { name: 'Highlighter', default_uom: 'pcs', category: 'Office Supplies' },
        { name: 'Glue Stick', default_uom: 'pcs', category: 'Office Supplies' },
        { name: 'Ruler (30cm)', default_uom: 'pcs', category: 'Office Supplies' },
        { name: 'Calculator (Basic)', default_uom: 'pcs', category: 'Office Supplies' },
        { name: 'Notebook (A5)', default_uom: 'pcs', category: 'Office Supplies' },
        { name: 'Toner Cartridge', default_uom: 'pcs', category: 'Office Supplies' },
        { name: 'Binder Clip (Assorted)', default_uom: 'pcs', category: 'Office Supplies' },
      ],
    },
    {
      category: 'Equipment',
      products: [
        { name: 'Desktop Computer', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Laptop', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Printer (Laser)', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Printer (Inkjet)', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Photocopier', default_uom: 'pcs', category: 'Equipment' },
        { name: 'UPS (Uninterruptible Power Supply)', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Office Chair', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Office Desk', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Filing Cabinet', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Conference Table', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Whiteboard', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Projector', default_uom: 'pcs', category: 'Equipment' },
        { name: 'CCTV Camera', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Fire Extinguisher', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Water Dispenser', default_uom: 'pcs', category: 'Equipment' },
        { name: 'Air Conditioner', default_uom: 'pcs', category: 'Equipment' },
      ],
    },
    {
      category: 'Merchandise',
      products: [
        { name: 'Product A (General)', default_uom: 'pcs', category: 'Merchandise' },
        { name: 'Product B (General)', default_uom: 'pcs', category: 'Merchandise' },
        { name: 'Product C (General)', default_uom: 'pcs', category: 'Merchandise' },
      ],
    },
    {
      category: 'Packaging',
      products: [
        { name: 'Carton Box (Small)', default_uom: 'pcs', category: 'Packaging' },
        { name: 'Carton Box (Medium)', default_uom: 'pcs', category: 'Packaging' },
        { name: 'Carton Box (Large)', default_uom: 'pcs', category: 'Packaging' },
        { name: 'Polybag', default_uom: 'pcs', category: 'Packaging' },
        { name: 'Bubble Wrap (Roll)', default_uom: 'roll', category: 'Packaging' },
        { name: 'Packing Tape (Clear)', default_uom: 'roll', category: 'Packaging' },
        { name: 'Packing Tape (Brown)', default_uom: 'roll', category: 'Packaging' },
      ],
    },
  ],
};

export function getIndustryPreset(industry: string): IndustryPreset | undefined {
  return PRESETS[industry];
}

export function getAllIndustryKeys(): string[] {
  return Object.keys(PRESETS);
}

export function getCatalog(industry?: string): CatalogCategory[] {
  if (industry && CATALOG[industry]) return CATALOG[industry];
  return CATALOG.general || [];
}

export function getMergedCatalog(industries: string[]): CatalogCategory[] {
  const seen = new Set<string>();
  const merged: CatalogCategory[] = [];
  for (const ind of industries) {
    const cat = CATALOG[ind];
    if (!cat) continue;
    for (const group of cat) {
      const existing = merged.find(g => g.category === group.category);
      if (existing) {
        for (const p of group.products) {
          const key = `${p.name}::${p.default_uom}`;
          if (!seen.has(key)) {
            seen.add(key);
            existing.products.push(p);
          }
        }
      } else {
        const fresh: CatalogCategory = { category: group.category, products: [] };
        for (const p of group.products) {
          const key = `${p.name}::${p.default_uom}`;
          if (!seen.has(key)) {
            seen.add(key);
            fresh.products.push(p);
          }
        }
        merged.push(fresh);
      }
    }
  }
  return merged;
}

export { PRESETS, CATALOG };
