

export const heroImages = [
  { src: '/images/hero/hero-skyscraper-nyc-night.jpg', alt: 'New York City skyline at night, USA' },
  { src: '/images/hero/hero-skyscraper-glass-modern.jpg', alt: 'Modern glass skyscraper architecture' },
  { src: '/images/hero/hero-skyscraper-sunset.jpg', alt: 'City skyline at sunset with towers' },
  { src: '/images/hero/hero-skyscraper-dubai.jpg', alt: 'Dubai Burj Khalifa skyline, UAE' },
  { src: '/images/hero/hero-skyscraper-hongkong.jpg', alt: 'Hong Kong harbour skyline panorama' },
  { src: '/images/hero/hero-skyscraper-shanghai.jpg', alt: 'Shanghai financial district skyscrapers' },
  { src: '/images/hero/hero-skyscraper-london.jpg', alt: 'London skyline at twilight, UK' },
  { src: '/images/hero/hero-skyscraper-singapore.jpg', alt: 'Singapore Marina Bay skyline' },
  { src: '/images/hero/hero-skyscraper-kualalumpur.jpg', alt: 'Kuala Lumpur Petronas Towers, Malaysia' },
  { src: '/images/hero/hero-skyscraper-chicago.jpg', alt: 'Chicago skyline, USA' },
  { src: '/images/hero/hero-1512453979798-5ea266f8880c.jpg', alt: 'Dubai Burj Khalifa skyline, UAE' },
  { src: '/images/hero/hero-1513635269975-59663e0ac1ad.jpg', alt: 'London skyline at twilight, UK' },
  { src: '/images/hero/hero-1502602898657-3e91760cbb34.jpg', alt: 'Paris city skyline, France' },
  { src: '/images/hero/hero-1525625293386-3f8f99389edd.jpg', alt: 'Singapore Supertrees skyline' },
  { src: '/images/hero/hero-1596422846543-75c6fc197f07.jpg', alt: 'Kuala Lumpur Petronas Towers, Malaysia' },
  { src: '/images/hero/hero-1524231757912-21f4fe3a7200.jpg', alt: 'Istanbul Bosphorus skyline, Turkey' },
  { src: '/images/hero/hero-1560969184-10fe8719e047.jpg', alt: 'Berlin modern architecture, Germany' },
  { src: '/images/hero/hero-1460472178825-e5240623afd5.jpg', alt: 'Modern skyscraper glass architecture' },
  { src: '/images/hero/hero-1487958449943-2429e8be8625.jpg', alt: 'Corporate tower modern architecture' },
  { src: '/images/hero/hero-1478391679764-b2d8b3cd1e94.jpg', alt: 'City skyline at sunset silhouette' },
  { src: '/images/hero/hero-1480714378408-67cf0d13bc1b.jpg', alt: 'Global financial district skyline' },
  { src: '/images/hero/hero-1477959858617-67f85cf4f1df.jpg', alt: 'Metropolitan skyline skyscrapers' },
  { src: '/images/hero/hero-1519501025264-65ba15a82390.jpg', alt: 'Downtown glass towers cityscape' },
  { src: '/images/hero/hero-1486406146926-c627a92ad1ab.jpg', alt: 'Corporate business district architecture' },
  { src: '/images/hero/hero-1449824913935-59a10b8d2000.jpg', alt: 'Urban canyon between skyscrapers' },
  { src: '/images/hero/hero-1504384308090-c894fdcc538d.jpg', alt: 'Modern glass office building facade' },
  { src: '/images/hero/hero-1446776811953-b23d57bd21aa.jpg', alt: 'Skyscraper reaching into clouds' },
  { src: '/images/hero/hero-1541888946425-d81bb19240f5.jpg', alt: 'Architecture construction skyscraper' },
  { src: '/images/hero/hero-1574227492706-f65b24c3688a.jpg', alt: 'Marina Bay Singapore skyline' },
  { src: '/images/hero/hero-1531219572328-a0171b4448a3.jpg', alt: 'London financial district Canary Wharf' },
  { src: '/images/hero/hero-1534430480872-3498386e7856.jpg', alt: 'Hong Kong skyline at night' },
  { src: '/images/hero/hero-1523731407965-2430cd12f5e4.jpg', alt: 'Shanghai financial district skyscrapers' },
  { src: '/images/hero/hero-1486325212027-8081e485255e.jpg', alt: 'Hong Kong harbour skyline panorama' },
  { src: '/images/hero/hero-1501594907352-04cda38ebc29.jpg', alt: 'San Francisco Golden Gate bridge' },
  { src: '/images/hero/hero-1514565131-fce0801e5785.jpg', alt: 'Toronto financial district skyline' },
  { src: '/images/hero/hero-1514924013411-cbf25faa35bb.jpg', alt: 'New York City skyline aerial view' },
  { src: '/images/hero/hero-1514395462725-fb4566210144.jpg', alt: 'Melbourne city skyline, Australia' },
  { src: '/images/hero/hero-1693464550496-8a6b114585b8.jpg', alt: 'Upper Hill Nairobi skyline, Kenya' },
  { src: '/images/hero/hero-1749058388308-744fdc8991ed.jpg', alt: 'Victoria Island modern skyline, Lagos' },
  { src: '/images/hero/hero-1771868453049-b7b4a4680b5c.jpg', alt: 'Urban development construction, Nairobi' },
  { src: '/images/hero/hero-1765246312031-87e7a216a543.jpg', alt: 'Chicago skyline across Lake Michigan, USA' },
];

export const businessTeamImages = [
  {
    src: '/images/team/collaborating.jpg',
    alt: 'Diverse business team collaborating in modern office',
  },
  {
    src: '/images/team/meeting.jpg',
    alt: 'Professional team meeting in corporate office',
  },
  {
    src: '/images/team/laptops.jpg',
    alt: 'Business team working with laptops in modern office',
  },
  {
    src: '/images/team/discussion.jpg',
    alt: 'Diverse professionals having discussion in office',
  },
];

export const statsData = [
  { value: 12500, suffix: '+', label: 'Businesses Served' },
  { value: 47, suffix: '+', label: 'Countries Worldwide' },
  { value: 28, suffix: 'M+', label: 'Daily Transactions' },
  { value: 4.2, suffix: 'M+', label: 'Invoices Generated' },
];

export const features = [
  { title: 'Inventory Management', desc: 'Real-time stock tracking, low-stock alerts, barcode scanning, and multi-warehouse management.' },
  { title: 'Sales & POS', desc: 'Fast point-of-sale with customer management, receipts, and integrated payment processing.' },
  { title: 'Accounting', desc: 'Double-entry accounting, general ledger, trial balance, and financial statements.' },
  { title: 'Expense Tracking', desc: 'Capture and categorize expenses, receipt scanning, and approval workflows.' },
  { title: 'Payroll Management', desc: 'Automated payroll with tax calculations, payslips, and statutory deductions.' },
  { title: 'Employee Management', desc: 'Employee records, attendance, leave management, and performance tracking.' },
  { title: 'Supplier Management', desc: 'Vendor records, purchase orders, supplier payments, and performance ratings.' },
  { title: 'Customer Management', desc: 'Customer database, communication history, credit limits, and loyalty programs.' },
  { title: 'Reports & Analytics', desc: 'Customizable reports, dashboards, KPIs, and business intelligence insights.' },
  { title: 'Cloud Sync', desc: 'Secure cloud backup with real-time synchronization across all your devices.' },
  { title: 'Offline Desktop', desc: 'Full functionality without internet. Sync automatically when reconnected.' },
  { title: 'Multi-Branch Support', desc: 'Manage multiple locations from one account with centralized reporting.' },
];

export const industries = [
  { name: 'Retail Shops', desc: 'POS, inventory, customer loyalty, and sales analytics.' },
  { name: 'Supermarkets', desc: 'Multi-department inventory, barcode scanning, supplier management.' },
  { name: 'Hardware Stores', desc: 'Stock tracking, supplier orders, job costing, quotations.' },
  { name: 'Pharmacies', desc: 'Expiry tracking, prescription management, supplier orders.' },
  { name: 'Restaurants', desc: 'Menu management, table orders, inventory, staff scheduling.' },
  { name: 'Wholesalers', desc: 'Bulk pricing, volume discounts, delivery management.' },
  { name: 'Manufacturers', desc: 'BOM, production costing, raw material tracking.' },
  { name: 'Bookshops', desc: 'Stock management, supplier orders, student accounts.' },
  { name: 'Electronics Stores', desc: 'Serial number tracking, warranty management, repairs.' },
  { name: 'Fashion Stores', desc: 'Size/color variants, seasonal inventory, supplier management.' },
  { name: 'Agribusiness', desc: 'Crop tracking, supplier payments, harvest recording.' },
  { name: 'Distributors', desc: 'Route management, delivery tracking, customer accounts.' },
];

export const benefits = [
  { title: 'Fast', desc: 'Lightning-quick performance even with large datasets.' },
  { title: 'Reliable', desc: '99.9% uptime with automatic failover protection.' },
  { title: 'Secure', desc: 'AES-256 encryption, role-based access, audit trails.' },
  { title: 'Offline Capable', desc: 'Work without internet. Sync when connected.' },
  { title: 'Cloud Sync', desc: 'Real-time synchronization across all devices.' },
  { title: 'Enterprise Ready', desc: 'Scalable from 1 to 1,000+ users.' },
  { title: 'Affordable', desc: 'Competitive pricing with no hidden fees.' },
  { title: 'Easy to Learn', desc: 'Intuitive interface with video tutorials.' },
  { title: 'Auto Updates', desc: 'Always up-to-date with the latest features.' },
  { title: 'Professional Support', desc: 'Dedicated support team ready to help.' },
  { title: 'Regular Improvements', desc: 'New features and updates every month.' },
  { title: 'Scalable', desc: 'Grows with your business. No migration needed.' },
];

export const testimonials = [
  {
    quote: 'BiasharaLedger transformed our operations. We manage 5 retail outlets from one dashboard — inventory, sales, payroll, and accounting. The offline desktop mode is a lifesaver when internet goes down.',
    name: 'James Kiprop',
    role: 'Owner',
    business: 'Nairobi Hardware Solutions',
    country: 'Kenya',
    industry: 'Hardware Store',
    rating: 5,
    initials: 'JK',
    color: 'from-brand/30 to-brand/10',
  },
  {
    quote: 'We switched from manual records to BiasharaLedger and saw immediate improvement. Stock management, supplier payments, and daily sales reports are now automated. Highly recommended for supermarkets.',
    name: 'Faith Nyambura',
    role: 'Operations Manager',
    business: 'Mombasa Fresh Mart',
    country: 'Kenya',
    industry: 'Supermarket',
    rating: 5,
    initials: 'FN',
    color: 'from-blue-600/30 to-blue-600/10',
  },
  {
    quote: 'As a wholesale distributor with 2,000+ SKUs, we needed robust inventory control. BiasharaLedger delivers. Barcode scanning, batch tracking, and automated reordering saved us countless hours.',
    name: 'Samuel Ochieng',
    role: 'Director',
    business: 'Lake Basin Wholesalers',
    country: 'Kenya',
    industry: 'Wholesale',
    rating: 5,
    initials: 'SO',
    color: 'from-amber-600/30 to-amber-600/10',
  },
  {
    quote: 'Managing prescriptions, expiries, and supplier orders was chaotic. BiasharaLedger streamlined everything. Our pharmacy now runs efficiently with real-time stock visibility.',
    name: 'Dr. Amina Hassan',
    role: 'Lead Pharmacist',
    business: 'Coastal Chemists Ltd',
    country: 'Kenya',
    industry: 'Pharmacy',
    rating: 5,
    initials: 'AH',
    color: 'from-emerald-600/30 to-emerald-600/10',
  },
];

export const pricingPlans = [
  {
    name: 'Basic',
    price: '5',
    period: '/month',
    desc: 'Essential accounting for solopreneurs and small shops.',
    popular: false,
    features: [
      'Double-entry bookkeeping', 'Invoicing & quotations',
      'Profit & Loss report', 'Balance Sheet', 'Trial Balance',
      'Expense tracking', 'Customer & supplier management', 'Email support',
    ],
    cta: 'Start Free Trial',
  },
  {
    name: 'Standard',
    price: '10',
    period: '/month',
    desc: 'Growing businesses with teams and payroll needs.',
    popular: true,
    features: [
      'Everything in Basic', 'HR & Payroll management',
      'General Ledger', 'Inventory management',
      'Multi-user access (up to 5)', 'Cash flow statements',
      'Receivables & payables aging', 'Priority support',
    ],
    cta: 'Start Free Trial',
  },
  {
    name: 'Premium',
    price: '15',
    period: '/month',
    desc: 'Full access for established businesses.',
    popular: false,
    features: [
      'Unlimited users', 'Everything in Standard', 'API access',
      'Multi-branch support', 'Budget vs actual reports',
      "Owner's equity statements", 'Tax reports', 'Audit trail',
      'Dedicated account manager', 'Phone & priority support',
    ],
    cta: 'Start Free Trial',
  },
];

export const hostingPlans = [
  {
    name: 'Free Tier',
    storage: '0.5 GB',
    price: 'Free',
    priceLabel: '$0',
    overage: '$0.50/GB/month',
    desc: 'Get started with basic cloud storage for your business data.',
    cta: 'Get Started',
    popular: false,
  },
  {
    name: 'Starter Hosting',
    storage: '5 GB',
    price: '$5',
    priceLabel: '$5/month',
    overage: '$0.50/GB/month overage',
    desc: 'Reliable cloud storage for growing businesses.',
    cta: 'Subscribe',
    popular: true,
  },
  {
    name: 'Growth Hosting',
    storage: '20 GB',
    price: '$15',
    priceLabel: '$15/month',
    overage: '$0.50/GB/month overage',
    desc: 'Ample storage for data-driven enterprises.',
    cta: 'Subscribe',
    popular: false,
  },
  {
    name: 'Enterprise Hosting',
    storage: '100 GB+',
    price: 'Custom',
    priceLabel: 'Custom pricing',
    overage: 'Negotiated overage',
    desc: 'Dedicated infrastructure for large organizations.',
    cta: 'Contact Sales',
    popular: false,
  },
];

export const backupPlans = [
  {
    name: 'Basic Backup',
    price: '$5',
    period: '/month',
    desc: 'Daily snapshots up to 10 GB',
    features: [
      'Daily automated backups', 'Up to 10 GB storage', '7-day retention',
      'One-click restore', 'Email notifications',
    ],
    cta: 'Add Backup Plan',
    popular: false,
  },
  {
    name: 'Advanced Backup',
    price: '$15',
    period: '/month',
    desc: 'Redundant backups across multiple servers',
    features: [
      'Real-time continuous backups', 'Multi-server redundancy', '30-day retention',
      'Instant file recovery', 'SLA-backed reliability',
      'Cross-region replication', 'Priority support',
    ],
    cta: 'Add Backup Plan',
    popular: true,
  },
];

export const cityLabels = [
  'Tokyo · Japan', 'Shanghai · China', 'Dubai · Burj Khalifa',
  'London · Twilight', 'Paris · Skyline', 'Singapore · Supertrees',
  'Kuala Lumpur · Petronas', 'Seoul · Night Skyline', 'Istanbul · Bosphorus', 'Berlin · Architecture',
  'Modern Skyscraper · Glass', 'Corporate Tower · Modern', 'City Skyline · Sunset',
  'Financial District · Global', 'Metropolitan · Skyline',
  'Glass Towers · Cityscape', 'Corporate · District', 'Urban · Canyon', 'Glass Office · Facade',
  'Skyscraper · Clouds', 'Glass Tower · Reflection', 'Beverly Hills · Architecture',
  'Construction · Skyscraper', 'Marina Bay · Singapore', 'London · Financial District',
  'Hong Kong · Night Skyline', 'Shanghai · Skyscrapers', 'Berlin · Business District', 'Sydney · Harbour',
  'Night Skyline · Cityscape', 'Hong Kong · Panorama',
  'San Francisco · Golden Gate', 'Toronto · Skyline',
  'New York · Aerial View', 'Sandton · Johannesburg', 'Melbourne · Australia',
  'Team · Collaboration', 'Team · Laptops', 'Corporate · Presentation', 'Professionals · Discussion',
  'Upper Hill · Nairobi', 'Victoria Island · Lagos', 'Urban Development · Nairobi', 'Chicago · USA',
];
