'use client';

import { useEffect, useState, useRef } from 'react';

function buildHTML(title: string, headers: string[], rows: string[][]) {
  const headRow = headers.map((h) => `<th style="color:#fff;padding:6px 8px;text-align:left;border:1px solid #c01515">${h}</th>`).join('');
  const bodyRows = rows.map(
    (r) => `<tr>${r.map((c) => `<td style="border:1px solid #ddd;padding:6px 8px">${c}</td>`).join('')}</tr>`
  ).join('\n');
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${title}</title>
<style>body{font-family:Arial,sans-serif;font-size:12px;padding:20px}
h2{color:#df1c1c}table{border-collapse:collapse;width:100%}
th{background:#df1c1c}td{border:1px solid #ddd;padding:6px 8px}
.footer{margin-top:20px;font-size:10px;color:#666}
@media print{body{padding:10px}}</style></head><body>
<h2>${title}</h2>
<table><thead><tr>${headRow}</tr></thead>
<tbody>${bodyRows}</tbody></table>
<p class="footer">Generated by BiasharaLedger</p></body></html>`;
}

export function TableDownload({ title, headers, rows }: { title: string; headers: string[]; rows: string[][] }) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  function downloadDOC() {
    const html = buildHTML(title, headers, rows);
    const blob = new Blob([html], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.replace(/\s+/g, '_')}.doc`;
    a.click();
    URL.revokeObjectURL(url);
    setOpen(false);
  }

  function downloadPDF() {
    const win = window.open('', '_blank');
    if (!win) return;
    const html = buildHTML(title, headers, rows);
    win.document.write(html.replace('</body>', '<script>window.print()</script></body>'));
    win.document.close();
    setOpen(false);
  }

  return (
    <div className="relative mt-4 pt-3 border-t border-border flex items-center gap-2" ref={ref}>
      <span className="text-xs text-[#666]">Download this report:</span>
      <button onClick={() => setOpen(!open)} className="text-xs px-3 py-1 rounded bg-brand text-white hover:bg-brand-hover">Download</button>
      {open && (
        <div className="absolute bottom-full left-0 mb-1 w-36 bg-white border border-border rounded-lg shadow-lg z-10">
          <button onClick={downloadDOC} className="block w-full text-left px-4 py-2 text-sm text-[#000000] hover:bg-surface rounded-t-lg">Word (.doc)</button>
          <button onClick={downloadPDF} className="block w-full text-left px-4 py-2 text-sm text-[#000000] hover:bg-surface rounded-b-lg">PDF</button>
        </div>
      )}
    </div>
  );
}
