export type ApiData = {
  grossSales: number; salesReturns: number; discounts: number; allowances: number;
  netSales: number;
  openingInventory: number; purchases: number; directCosts: number; debitNotes: number;
  closingInventory: number; costOfGoodsSold: number; grossProfit: number;
  adminExpenses: number; sellingDistributionExpenses: number; generalOperatingExpenses: number;
  salariesTotal: number; depreciationExpense: number; totalOperatingExpenses: number;   operatingProfit: number;
  ebitda: number;
  grossMarginPercent: number;
  netMarginPercent: number;
  grossSalesPrior: number; salesReturnsPrior: number; discountsPrior: number;
  netSalesPrior: number; purchasesPrior: number; debitNotesPrior: number;
  costOfGoodsSoldPrior: number; grossProfitPrior: number;
  grossMarginPercentPrior: number; netMarginPercentPrior: number;
  adminExpensesPrior: number; sellingDistributionExpensesPrior: number; generalOperatingExpensesPrior: number;
  salariesTotalPrior: number; depreciationExpensePrior: number; totalOperatingExpensesPrior: number;
  operatingProfitPrior: number; ebitdaPrior: number;
  otherIncomePrior: number; otherExpensesPrior: number;
  profitBeforeTaxPrior: number; taxesPrior: number; netProfitPrior: number;
  expenseByCategoryPrior: { category: string; total: number; count: number }[];
  cashOperatingInflowPrior: number; cashOperatingOutflowPrior: number; netOperatingCashFlowPrior: number;
  cashSupplierPaymentsPrior: number; cashExpensePaymentsPrior: number; cashSalaryPaymentsPrior: number;
  financingInflowPrior: number; financingOutflowPrior: number; netFinancingCashFlowPrior: number;
  netCashFlowPrior: number;
  otherIncome: number; otherExpenses: number; profitBeforeTax: number; taxes: number;
  netProfit: number;
  totalRevenue: number; totalCreditNotes: number; netRevenue: number;
  totalPurchases: number; totalDebitNotes: number;
  totalExpenses: number; totalSalaries: number;
  operatingExpenses: number;
  cashOnHand: number; accountsReceivable: number; accountsPayable: number;
  inventoryValue: number;
  currentAssets: number; nonCurrentAssets: number; totalAssets: number;
  currentLiabilities: number; nonCurrentLiabilities: number; totalLiabilities: number;
  totalEquity: number;
  retainedEarnings: number;
  receivables: { total: number; open: number; overdue: number };
  payables: { total: number; open: number; overdue: number };
  cashOperatingInflow: number; cashOperatingOutflow: number;
  netOperatingCashFlow: number;
  cashSupplierPayments: number; cashExpensePayments: number; cashSalaryPayments: number;
  investingInflow: number; investingOutflow: number; netInvestingCashFlow: number;
  financingInflow: number; financingOutflow: number; netFinancingCashFlow: number;
  netCashFlow: number;
  monthlyCash: { month: string; incoming: number; outgoing: number; profit: number }[];
  trialBalance: { account: string; type: string; balance: number }[];
  generalLedger: { id: string; type: string; amount: number; detail: string; date: string; created_at: string; runningBalance: number }[];
  receivablesAging: { bucket: string; total: number; count: number }[];
  payablesAging: { bucket: string; total: number; count: number }[];
  expenseByCategory: { category: string; total: number; count: number }[];
  salariesDetail: { total: number; count: number };
  salesByCustomer: { company_name: string; total: number; count: number }[];
  inventoryValuation: { totalItems: number; totalValue: number; items: any[]; message: string };
  budgetVsActual: { category: string; budget: number; actual: number; variance: number; variancePercent: number; status: string }[];
  equityReport: { retainedEarnings: number; capitalContributions: number; withdrawals: number; currentPeriodProfit: number; totalEquity: number };
  taxReport: { vatOutput: number; vatInput: number; vatPayable: number; vatPayableBalance: number; incomeTaxPayable: number; taxableSales: number; taxablePurchases: number; standardRatedSales: number; zeroRatedSales: number; standardRatedPurchases: number; zeroRatedPurchases: number; incomeTaxRate: number; profitBeforeTax: number; incomeTax: number; netProfitAfterTax: number; note: string };
  fixedAssets: { count: number; totalCost: number; totalDepreciation: number; totalBookValue: number };
  auditTrail: { action: string; id: string; amount: number; created_at: string }[];
};

export const cfmt = (n: number) => {
  const sym = 'KSh';
  return `${sym} ${(n || 0).toLocaleString('en-US', { minimumFractionDigits: 2 })}`;
};
